package it.infocert.eigor.api.utils;

import java.util.HashSet;
import java.util.Set;

public class JavaReflections implements IReflections {

    @Override
    @SuppressWarnings("unchecked")
    public <T> Set<Class<? extends T>> getSubTypesOf(Class<T> type) {

        if(type == null) throw new IllegalArgumentException("Type cannot be null.");
        if(!type.getName().equals("it.infocert.eigor.model.core.model.BTBG")) throw new IllegalArgumentException("Unsupported type " + type.getName());

        HashSet<Class<? extends T>> result = new HashSet<>();
        try {
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0000Invoice"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0001InvoiceNote"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0002ProcessControl"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0003PrecedingInvoiceReference"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0004Seller"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0005SellerPostalAddress"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0006SellerContact"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0007Buyer"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0008BuyerPostalAddress"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0009BuyerContact"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0010Payee"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0011SellerTaxRepresentativeParty"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0012SellerTaxRepresentativePostalAddress"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0013DeliveryInformation"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0014InvoicingPeriod"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0015DeliverToAddress"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0016PaymentInstructions"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0017CreditTransfer"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0018PaymentCardInformation"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0019DirectDebit"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0020DocumentLevelAllowances"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0021DocumentLevelCharges"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0022DocumentTotals"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0023VatBreakdown"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0024AdditionalSupportingDocuments"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0025InvoiceLine"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0026InvoiceLinePeriod"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0027InvoiceLineAllowances"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0028InvoiceLineCharges"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0029PriceDetails"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0030LineVatInformation"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0031ItemInformation"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BG0032ItemAttributes"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0001InvoiceNumber"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0002InvoiceIssueDate"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0003InvoiceTypeCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0005InvoiceCurrencyCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0006VatAccountingCurrencyCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0007ValueAddedTaxPointDate"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0008ValueAddedTaxPointDateCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0009PaymentDueDate"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0010BuyerReference"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0011ProjectReference"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0012ContractReference"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0013PurchaseOrderReference"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0014SalesOrderReference"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0015ReceivingAdviceReference"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0016DespatchAdviceReference"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0017TenderOrLotReference"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0018InvoicedObjectIdentifierAndSchemeIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0019BuyerAccountingReference"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0020PaymentTerms"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0021InvoiceNoteSubjectCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0022InvoiceNote"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0023BusinessProcessType"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0024SpecificationIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0025PrecedingInvoiceReference"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0026PrecedingInvoiceIssueDate"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0027SellerName"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0028SellerTradingName"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0029SellerIdentifierAndSchemeIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0030SellerLegalRegistrationIdentifierAndSchemeIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0031SellerVatIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0032SellerTaxRegistrationIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0033SellerAdditionalLegalInformation"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0034SellerElectronicAddressAndSchemeIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0035SellerAddressLine1"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0036SellerAddressLine2"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0037SellerCity"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0038SellerPostCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0039SellerCountrySubdivision"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0040SellerCountryCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0041SellerContactPoint"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0042SellerContactTelephoneNumber"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0043SellerContactEmailAddress"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0044BuyerName"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0045BuyerTradingName"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0046BuyerIdentifierAndSchemeIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0047BuyerLegalRegistrationIdentifierAndSchemeIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0048BuyerVatIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0049BuyerElectronicAddressAndSchemeIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0050BuyerAddressLine1"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0051BuyerAddressLine2"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0052BuyerCity"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0053BuyerPostCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0054BuyerCountrySubdivision"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0055BuyerCountryCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0056BuyerContactPoint"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0057BuyerContactTelephoneNumber"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0058BuyerContactEmailAddress"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0059PayeeName"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0060PayeeIdentifierAndSchemeIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0061PayeeLegalRegistrationIdentifierAndSchemeIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0062SellerTaxRepresentativeName"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0063SellerTaxRepresentativeVatIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0064TaxRepresentativeAddressLine1"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0065TaxRepresentativeAddressLine2"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0066TaxRepresentativeCity"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0067TaxRepresentativePostCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0068TaxRepresentativeCountrySubdivision"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0069TaxRepresentativeCountryCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0070DeliverToPartyName"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0071DeliverToLocationIdentifierAndSchemeIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0072ActualDeliveryDate"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0073InvoicingPeriodStartDate"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0074InvoicingPeriodEndDate"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0075DeliverToAddressLine1"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0076DeliverToAddressLine2"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0077DeliverToCity"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0078DeliverToPostCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0079DeliverToCountrySubdivision"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0080DeliverToCountryCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0081PaymentMeansTypeCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0082PaymentMeansText"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0083RemittanceInformation"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0084PaymentAccountIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0085PaymentAccountName"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0086PaymentServiceProviderIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0087PaymentCardPrimaryAccountNumber"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0088PaymentCardHolderName"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0089MandateReferenceIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0090BankAssignedCreditorIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0091DebitedAccountIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0092DocumentLevelAllowanceAmount"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0093DocumentLevelAllowanceBaseAmount"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0094DocumentLevelAllowancePercentage"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0095DocumentLevelAllowanceVatCategoryCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0096DocumentLevelAllowanceVatRate"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0097DocumentLevelAllowanceReason"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0098DocumentLevelAllowanceReasonCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0099DocumentLevelChargeAmount"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0100DocumentLevelChargeBaseAmount"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0101DocumentLevelChargePercentage"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0102DocumentLevelChargeVatCategoryCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0103DocumentLevelChargeVatRate"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0104DocumentLevelChargeReason"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0105DocumentLevelChargeReasonCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0106SumOfInvoiceLineNetAmount"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0107SumOfAllowancesOnDocumentLevel"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0108SumOfChargesOnDocumentLevel"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0109InvoiceTotalAmountWithoutVat"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0110InvoiceTotalVatAmount"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0111InvoiceTotalVatAmountInAccountingCurrency"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0112InvoiceTotalAmountWithVat"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0113PaidAmount"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0114RoundingAmount"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0115AmountDueForPayment"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0116VatCategoryTaxableAmount"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0117VatCategoryTaxAmount"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0118VatCategoryCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0119VatCategoryRate"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0120VatExemptionReasonText"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0121VatExemptionReasonCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0122SupportingDocumentReference"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0123SupportingDocumentDescription"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0124ExternalDocumentLocation"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0125AttachedDocumentAndAttachedDocumentMimeCodeAndAttachedDocumentFilename"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0126InvoiceLineIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0127InvoiceLineNote"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0128InvoiceLineObjectIdentifierAndSchemeIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0129InvoicedQuantity"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0130InvoicedQuantityUnitOfMeasureCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0131InvoiceLineNetAmount"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0132ReferencedPurchaseOrderLineReference"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0133InvoiceLineBuyerAccountingReference"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0134InvoiceLinePeriodStartDate"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0135InvoiceLinePeriodEndDate"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0136InvoiceLineAllowanceAmount"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0137InvoiceLineAllowanceBaseAmount"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0138InvoiceLineAllowancePercentage"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0139InvoiceLineAllowanceReason"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0140InvoiceLineAllowanceReasonCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0141InvoiceLineChargeAmount"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0142InvoiceLineChargeBaseAmount"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0143InvoiceLineChargePercentage"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0144InvoiceLineChargeReason"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0145InvoiceLineChargeReasonCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0146ItemNetPrice"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0147ItemPriceDiscount"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0148ItemGrossPrice"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0149ItemPriceBaseQuantity"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0150ItemPriceBaseQuantityUnitOfMeasureCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0151InvoicedItemVatCategoryCode"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0152InvoicedItemVatRate"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0153ItemName"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0154ItemDescription"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0155ItemSellerSIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0156ItemBuyerSIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0157ItemStandardIdentifierAndSchemeIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0158ItemClassificationIdentifierAndSchemeIdentifierAndSchemeVersionIdentifier"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0159ItemCountryOfOrigin"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0160ItemAttributeName"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0161ItemAttributeValue"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0162SellerAddressLine3"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0163BuyerAddressLine3"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0164TaxRepresentativeAddressLine3"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.BT0165DeliverToAddressLine3"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.AbstractBT"));
            result.add((Class<? extends T>) Class.forName("it.infocert.eigor.model.core.model.AbstractBTBG"));


        } catch (ClassNotFoundException e) {
            throw new RuntimeException(e);
        }
        return result;
    }

}
