package it.infocert.eigor.model.core.enums;

public enum Untdid4451InvoiceNoteSubjectCode {

    AAA(false,"Goods description", "[7002] Plain language description of the nature of the for banking, Customs, statistical or transport purposes, avoiding unnecessary detail (Generic term)."),
    /** Terms of payements */
    AAB(false,"Terms of payments", "[4276] Conditions of payment between the parties to a transaction (generic term)."),
    AAC(false,"Dangerous goods additional information", "Additional information concerning dangerous goods."),
    AAD(false,"Dangerous goods, technical name", "Proper shipping name, supplemented as necessary with the correct technical name, by which a dangerous substance or article may be correctly identified or which is sufficiently informative to permit identification by reference to generally available literature."),
    AAE(false,"Acknowledgement description", "The content of an acknowledgement."),
    AAF(false,"Rate additional information", "Specific details applying to rates."),
    AAG(false,"Party instructions", "Indicates that the segment contains instructions to be passed on to the identified party."),
    AAH(false,"Customs information", "[4034] Information entered by Customs on the CIM."),
    AAI(false,"General information", "Self explanatory."),
    AAJ(false,"Additional conditions of sale/purchase", "Additional conditions specific to this order or project."),
    AAK(false,"Price conditions", "Information on the price conditions that are expected or given."),
    AAL(false,"Goods dimensions in characters", "Expression of a number in characters as length of ten meters."),
    AAM(false,"Equipment re-usage restrictions", "Technical or commercial reasons why a piece of equipment may not be re-used after the current transport terminates."),
    AAN(false,"Handling restriction", "Restrictions in handling depending on the technical characteristics of the piece of equipment or on the nature of the goods."),
    AAO(false,"Error description (free text)", "Error described by a free text."),
    AAP(false,"Response (free text)", "Free text of the response to a communication."),
    AAQ(false,"Package content's description", "Self explanatory."),
    AAR(false,"Terms of delivery", "(4053) Free text of the non Incoterms terms of delivery. For Incoterms, use: 4053."),
    AAS(false,"Bill of lading remarks", "Self explanatory."),
    AAT(false,"Mode of settlement information", "Free text information on an IATA Air Waybill to indicate means by which account is to be settled."),
    AAU(false,"Consignment invoice information", "Self explanatory."),
    AAV(false,"Clearance invoice information", "Self explanatory."),
    AAW(false,"Letter of credit information", "Self explanatory."),
    AAX(false,"License information", "Self explanatory."),
    AAY(false,"Certification statements", "Self explanatory."),
    AAZ(false,"Additional export information", "Self explanatory."),
    ABA(false,"Tariff statements", "Self explanatory."),
    ABC(false,"Conditions of sale or purchase", "Additional information regarding terms and conditions which apply to the transaction."),
    ABD(false,"Nature of transaction", "An indication for customs of the type of contract under which goods are supplied."),
    ABE(false,"Additional terms and/or conditions (documentary credit)", "Additional terms and/or conditions to the documentary credit."),
    ABF(false,"Instructions or information about standby documentary credit", "Instruction or information about a standby documentary credit."),
    ABG(false,"Instructions or information about partial shipment(s)", "Instructions or information about partial shipment(s)."),
    ABH(false,"Instructions or information about transhipment(s)", "Instructions or information about transhipment(s)."),
    ABI(false,"Additional handling instructions documentary credit", "Additional handling instructions for a documentary credit."),
    ABJ(false,"Domestic routing information", "Self explanatory."),
    ABK(false,"Chargeable category of equipment", "Equipment types are coded by category for financial purposes."),
    ABL(false,"Government information", "Self explanatory."),
    ABM(false,"Onward routing information", "Self explanatory."),
    ABN(false,"Accounting information", "Self explanatory."),
    ABO(false,"Discrepancy information", "Free text or coded information to indicate a specific discrepancy."),
    ABP(false,"Confirmation instructions", "Documentary credit confirmation instructions."),
    ABQ(false,"Method of issuance", "Method of issuance of documentary credit."),
    ABR(false,"Documents delivery instructions", "Delivery instructions for documents required under a documentary credit."),
    ABS(false,"Additional conditions", "Additional conditions to the issuance of a documentary credit."),
    ABT(false,"Information/instructions about additional amounts covered", "Additional amounts information/instruction."),
    ABU(false,"Deferred payment termed additional", "Additional terms concerning deferred payment."),
    ABV(false,"Acceptance terms additional", "Additional terms concerning acceptance."),
    ABW(false,"Negotiation terms additional", "Additional terms concerning negotiation."),
    ABX(false,"Document name and documentary requirements", "Document name and documentary requirements."),
    ABY(false,"Regulatory information", "The free text contains information for regulatory authority."),
    ABZ(false,"Instructions/information about revolving documentary credit", "Instructions/information about a revolving documentary credit."),
    ACA(false,"Documentary requirements", "Specification of the documentary requirements."),
    ACB(false,"Additional information", "Self explanatory."),
    ACC(false,"Factor assignment clause", "Assignment based on an agreement between seller and factor."),
    ACD(false,"Reason", "Reason for a request or response."),
    ACE(false,"Dispute", "A notice, usually from buyer to seller, that something was found wrong with goods delivered or the services rendered, or with the related invoice."),
    ACF(false,"Additional attribute information", "The text refers to information about an additional attribute not otherwise specified."),
    ACG(false,"Absence declaration", "A declaration on the reason of the absence."),
    ACH(false,"Aggregation statement", "A statement on the way a specific variable or set of variables has been aggregated."),
    ACI(false,"Compilation statement", "A statement on the compilation status of an array or other set of figures or calculations."),
    ACJ(false,"Definitional exception", "An exception to the agreed definition of a term, concept, formula or other object."),
    ACK(false,"Privacy statement", "A statement on the privacy or confidential nature of an object."),
    ACL(false,"Quality statement", "A statement on the quality of an object."),
    ACM(false,"Statistical description", "The description of a statistical object such as a value list, concept, or structure definition."),
    ACN(false,"Statistical definition", "The definition of a statistical object such as a value list, concept, or structure definition."),
    ACO(false,"Statistical name", "The name of a statistical object such as a value list, concept or structure definition."),
    ACP(false,"Statistical title", "The title of a statistical object such as a value list, concept, or structure definition."),
    ACQ(false,"Off-dimension information", "Information relating to differences between the actual transport dimensions and the normally applicable dimensions."),
    ACR(false,"Unexpected stops information", "Information relating to unexpected stops during a conveyance."),
    ACS(false,"Principles", "Text subject is principles section of the UN/EDIFACT rules for presentation of standardized message and directories documentation."),
    ACT(false,"Terms and definition", "Text subject is terms and definition section of the UN/EDIFACT rules for presentation of standardized message and directories documentation."),
    ACU(false,"Segment name", "Text subject is segment name."),
    ACV(false,"Simple data element name", "Text subject is name of simple data element."),
    ACW(false,"Scope", "Text subject is scope section of the UN/EDIFACT rules for presentation of standardized message and directories documentation."),
    ACX(false,"Message type name", "Text subject is name of message type."),
    ACY(false,"Introduction", "Text subject is introduction section of the UN/EDIFACT rules for presentation of standardized message and directories documentation."),
    ACZ(false,"Glossary", "Text subject is glossary section of the UN/EDIFACT rules for presentation of standardized message and directories documentation."),
    ADA(false,"Functional definition", "Text subject is functional definition section of the UN/EDIFACT rules for presentation of standardized message and directories documentation."),
    ADB(false,"Examples", "Text subject is examples as given in the example(s) section of the UN/EDIFACT rules for presentation of standardized message and directories documentation."),
    ADC(false,"Cover page", "Text subject is cover page of the UN/EDIFACT rules for presentation of standardized message and directories documentation."),
    ADE(false,"Code value name", "Text subject is name of code value."),
    ADF(false,"Code list name", "Text subject is name of code list."),
    ADG(false,"Clarification of usage", "Text subject is an explanation of the intended usage of a segment or segment group."),
    ADH(false,"Composite data element name", "Text subject is name of composite data element."),
    ADI(false,"Field of application", "Text subject is field of application of the UN/EDIFACT rules for presentation of standardized message and directories documentation."),
    ADJ(false,"Type of assets and liabilities", "Information describing the type of assets and liabilities."),
    ADK(false,"Promotion information", "The text contains information about a promotion."),
    ADL(false,"Meter condition", "Description of the condition of a meter."),
    ADM(false,"Meter reading information", "Information related to a particular reading of a meter."),
    ADN(false,"Type of transaction reason", "Information describing the type of the reason of transaction."),
    ADO(false,"Type of survey question", "Type of survey question."),
    ADP(true,"Carrier's agent counter information", "Information for use at the counter of the carrier's goods sufficient to identify them at the level required agent."),
    ADQ(true,"Description of work item on equipment", "Description or code for the operation to be executed on the equipment."),
    ADR(true,"Message definition", "Text subject is message definition."),
    ADS(true,"Booked item information", "Information pertaining to a booked item."),
    ADT(true,"Source of document", "Text subject is source of document."),
    ADU(true,"Note", "Text subject is note."),
    ADV(true,"Fixed part of segment clarification text", "Text subject is fixed part of segment clarification text."),
    ADW(true,"Characteristics of goods", "Description of the characteristics of goods in addition to the description of the goods [7002]."),
    ADX(true,"Additional discharge instructions", "Special discharge instructions concerning the goods."),
    ADY(true,"Container stripping instructions", "Instructions regarding the stripping of container(s)."),
    ADZ(true,"CSC (Container Safety Convention) plate information", "Information on the CSC (Container Safety Convention) plate that is attached to the container."),
    AEA(true,"Cargo remarks", "Additional remarks concerning the cargo."),
    AEB(true,"Temperature control instructions", "Instruction regarding the temperature control of the cargo."),
    AEC(true,"Text refers to expected data", "Remarks refer to data that was expected."),
    AED(true,"Text refers to received data", "Remarks refer to data that was received."),
    AEE(true,"Section clarification text", "Text subject is section clarification text."),
    ALC(false,"Allowance/charge information", "Information referring to allowance/charge."),
    ALL(false,"All documents", "The note implies to all documents."),
    ARR(false,"Arrival conditions", "Conditions under which arrival takes place."),
    AUT(false,"Authentication", "Name, code, password etc. given for authentication purposes."),
    BLC(false,"Bill of lading clause", "Clause on the bill of lading regarding the cargo being shipped."),
    BLR(false,"Transport document remarks", "Remarks concerning the complete consignment to be printed on the bill of lading."),
    CCI(false,"Customs clearance instructions", "Any coded or clear instruction agreed by customer and carrier regarding the declaration of the goods."),
    CEX(false,"Customs clearance instructions export", "Any coded or clear instruction agreed by customer and carrier regarding the export declaration of the goods."),
    CHG(false,"Change information", "Note contains change information."),
    CIP(false,"Customs clearance instruction import", "Any coded or clear instruction agreed by customer and carrier regarding the import declaration of the goods."),
    CLP(false,"Clearance place requested", "Name of the place where Customs clearance is asked to be executed as requested by the consignee/consignor."),
    CLR(false,"Loading remarks", "Instructions concerning the loading of the container."),
    COI(false,"Order information", "Additional information related to an order."),
    CUR(false,"Customer remarks", "Remarks from or for a supplier of goods or services."),
    CUS(false,"Customs declaration information", "Note contains customs declaration information."),
    DAR(false,"Damage remarks", "Remarks concerning damage on the cargo."),
    DCL(false,"Declaration", "[4020] Text of a declaration made by the issuer of the document (CIM 12)."),
    DEL(false,"Delivery information", "Information about delivery."),
    DIN(false,"Delivery instructions", "Instructions regarding the delivery of the cargo."),
    DOC(false,"Documentation instructions", "Self explanatory."),
    DUT(false,"Duty declaration", "Self explanatory."),
    EUR(false,"Effective used routing", "Physical route effectively used for the movement of the means of transport."),
    FBC(false,"First block to be printed on the transport contract", "Self explanatory."),
    GBL(false,"Government bill of lading information", "Free text information on a transport document to indicate payment information by Government Bill of Lading."),
    GEN(false,"Entire transaction set", "Note is general in nature, applies to entire transaction segment."),
    GS7(false,"Further information concerning GGVS par. 7", "Special permission for road transport of certain goods in the German dangerous goods regulation for road transport."),
    HAN(false,"Handling instructions", "[4078] Instructions on how specified goods, packages or containers should be handled."),
    HAZ(false,"Hazard information", "Self explanatory."),
    ICN(false,"Information for consignee", "[4070] Any remark given for the information of the consignee (CIM 21)."),
    IIN(false,"Insurance instructions", "Instructions regarding the cargo insurance."),
    IMI(false,"CoreInvoice mailing instructions", "Instructions as to which freight and charges components have to be mailed to whom."),
    IND(false,"Commercial invoice item description", "Free text describing goods on a commercial invoice line."),
    INS(false,"Insurance information", "Specific note contains insurance information."),
    INV(false,"CoreInvoice instruction", "Note contains invoice instructions."),
    IRP(false,"Information for railway purpose", "[4090] Date entered by railway stations when required, e.g. specified trains, additional sheets for freight calculations, special measures, etc.. (CIM 8)."),
    ITR(false,"Inland transport details", "Information concerning the pre-carriage to the port of discharge if by other means than a vessel."),
    ITS(false,"Testing instructions", "Instructions regarding the testing that is required to be carried out on the items in the transaction."),
    LIN(false,"Line item", "Note contains line item information."),
    LOI(false,"Loading instruction", "Instructions where specified packages or containers are to be loaded on a means of transport."),
    MCO(false,"Miscellaneous charge order", "Free text accounting information on an IATA Air Waybill to indicate payment information by Miscellaneous charge order."),
    MKS(false,"Additional marks/numbers information", "Self explanatory."),
    ORI(false,"Order instruction", "Free text contains order instructions."),
    OSI(false,"Other service information", "General information created by the sender of general or specific value."),
    PAC(false,"Packing/marking information", "Information regarding the packaging and/or marking of goods."),
    PAI(false,"Payment instructions information", "The free text contains payment instructions information relevant to the message."),
    PAY(false,"Payables information", "Note contains payables information."),
    PKG(false,"Packaging information", "Note contains packaging instructions."),
    PKT(false,"Packaging terms information", "Self explanatory."),
    PMD(false,"Payment detail/remittance information", "The free text contains payment details."),
    PMT(false,"Payment information", "Note contains payments information."),
    PRD(false,"Product information", "Self explanatory."),
    PRF(false,"Price calculation formula", "Additional information regarding the price formula used for calculating the item price."),
    PRI(false,"Priority information", "Note contains priority information."),
    PUR(false,"Purchasing information", "Note contains purchasing information."),
    QIN(false,"Quarantine instructions", "Instructions regarding quarantine, i.e. the period during which an arriving vessel, including its equipment, cargo, crew or passengers, suspected to carry or carrying a contagious disease is detained in strict isolation to prevent the spread of such a disease."),
    QQD(false,"Quality demands/requirements", "Specification of the quality/performance expectations or standards to which the items must conform."),
    QUT(false,"Quotation instruction/information", "Note contains quotation information."),
    RAH(false,"Risk and handling information", "Information concerning risks induced by the goods and/or handling instruction."),
    REG(false,"Regulatory information", "The free text contains information for regulatory authority."),
    RET(false,"Return to origin information", "Free text information on an IATA Air Waybill to indicate consignment returned because of non delivery."),
    REV(false,"Receivables", "Description to be provided."),
    RQR(false,"Requested routes/routing instructions", "[3074] Names of places via which the consignor requests a consignment to be routed."),
    RQT(false,"Tariffs and route requested", "[4120] Stipulation of the tariffs to be applied showing,where applicable, special-agreement numbers or references indication of routes by frontier points or by frontier stations and, when necessary, by transit stations between."),
    SAF(false,"Safety information", "Self explanatory."),
    SIC(false,"Sender's instruction to carrier", "[4284] Instructions given and declarations made by the sender to the carrier concerning Customs, insurance, and other formalities."),
    SIN(false,"Special instructions", "Special instructions like licence no, high value, handle with care, glass."),
    SLR(false,"Ship line requested", "Shipping line requested to be used for traffic between European continent and U.K. for Ireland."),
    SPA(false,"Special permission for transport, generally", "Statement that a special permission has been obtained for the transport (and/or routing) in general, and reference to such permission."),
    SPG(false,"Special permission concerning the goods to be transported", "Statement that a special permission has been obtained for the transport (and/or routing) of the goods specified, and reference to such permission."),
    SPH(false,"Special handling", "Note contains special handling information."),
    SPP(false,"Special permission concerning package", "Statement that a special permission has been obtained for the packaging, and reference to such permission."),
    SPT(false,"Special permission concerning transport means", "Statement that a special permission has been obtained for the use of the means transport, and reference to such permission."),
    SRN(false,"Subsidiary risk number (IATA/DGR)", "Number(s) of subsidiary risks, induced by the goods, according to the valid classification."),
    SSR(false,"Special service request", "Request for a special service concerning the transport of the goods."),
    SUR(false,"Supplier remarks", "Remarks from or for a supplier of goods or services."),
    TCA(false,"Tariff and class applied", "[5430] Specification of tariff applied (CIM 55)."),
    TDT(false,"Transport details remarks", "Additional information related to transport details."),
    TRA(false,"Transportation information", "General information regarding the transport of the cargo."),
    TRR(false,"Requested tariff", "Stipulation of the tariffs to be applied showing, where applicable, special agreement numbers or references."),
    TXD(false,"Tax declaration", "Description to be provided."),
    WHI(false,"Warehouse instruction/information", "Note contains warehouse information."),
    ZZZ(false,"Mutually defined", "Note contains information mutually defined by trading partners.");

    private boolean hasPlusSign;
    private String shortDescritpion;
    private String longDescription;

    Untdid4451InvoiceNoteSubjectCode(boolean hasPlusSign, String shortDescritpion, String longDescription) {
        this.hasPlusSign = hasPlusSign;
        this.shortDescritpion = shortDescritpion;
        this.longDescription = longDescription;
    }

    public String toDetailedString() {
        return String.format("%s%s|%s|%s", (this.hasPlusSign ? "+":""), toString(), shortDescritpion, longDescription);
    }

    @Override
    public String toString() {
        return super.toString() + " " + shortDescritpion;
    }
}
